package io.thinkinglabs;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.Map;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        InvoiceEmailer classUnderTest = new InvoiceEmailer(
                new FeatureDecisions(
                        new Features(
                                Map.of("next-gen-ecomm", Boolean.TRUE))));
        assertEquals(new Email(), classUnderTest.generateInvoiceEmail(new Invoice()));
    }
}
