package io.thinkinglabs;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        InvoiceEmailer classUnderTest = new InvoiceEmailer(new Features());
        assertEquals(new Email(), classUnderTest.generateInvoiceEmail(new Invoice()));
    }
}
