package io.thinkinglabs;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class InvoiceEmailer
{

    private final FeatureDecisions featureDecisions;

    public InvoiceEmailer(final FeatureDecisions featureDecisions) {
        this.featureDecisions = featureDecisions;
    }

    public Email generateInvoiceEmail(final Invoice invoice) {
        Email baseEmail = buildEmailForInvoice(invoice);
        if (featureDecisions.includeOrderCancellationInEmail()) {
            return addOrderCancellationContentToBaseEmail(baseEmail);
        } else {
            return baseEmail;
        }
    }

    private Email addOrderCancellationContentToBaseEmail(final Email baseEmail)
    {
        return baseEmail;
    }

    private Email buildEmailForInvoice(final Invoice invoice)
    {
        return new Email();
    }
}
