package io.thinkinglabs;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class InvoiceEmailer
{
    private final AddContentToEmail addContentToEmail;

    public InvoiceEmailer(final AddContentToEmail addContentToEmail) {

        this.addContentToEmail = addContentToEmail;
    }

    public Email generateInvoiceEmail(final Invoice invoice) {
        Email baseEmail = buildEmailForInvoice(invoice);
        return addContentToEmail.addContent(baseEmail);
    }

    private Email buildEmailForInvoice(final Invoice invoice)
    {
        return new Email("blablabla");
    }
}
