package io.thinkinglabs;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class InvoiceEmailer
{

    private final Features features;

    public InvoiceEmailer(final Features features) {
        this.features = features;
    }

    public Email generateInvoiceEmail(final Invoice invoice) {
        Email baseEmail = buildEmailForInvoice(invoice);
        if (features.isEnabled("next-gen-ecomm")) {
            return addOrderCancellationContentToBaseEmail(baseEmail);
        } else {
            return baseEmail;
        }
    }

    private Email addOrderCancellationContentToBaseEmail(final Email baseEmail)
    {
        return baseEmail;
    }

    private Email buildEmailForInvoice(final Invoice invoice)
    {
        return new Email();
    }
}
